# Tensors
Tensors are mathematical objects, don't forget that. In Pytorch, you will probably see them as multi-dimensional arrays of real numbers, and in general, that's what they are most used as. However, they could contain any mathematical object that is part of a vector space with its corresponding operations and field.

In Pytorch, tensors are objects (just like everything else in Python), and they are initialized with a multi-dimensional array of numbers (except for the scalar tensors). There are four types: scalars, vectors, matrices and tensors (3D and above).

## Scalars

In [2]:
import torch
print("SCALAR")
scalar: torch.Tensor = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.shape)

SCALAR
tensor(7)
0
torch.Size([])


- The ``__str__`` magic method prints the definition of the tensor without the torch module.
- The ``ndim`` attribute returns the number of dimensions of the tensor or its rank.
  > You could see it as the amount of sub-indices you need to point to one component. For ex., the components of a vector will only need one to point to any axis of the vector's coordinate system, whereas matrices components will require two: One pointing to the column (vector) and one pointing to some axis of the coordinate system. In consequence, scalars won't need subindices because they need to point to the same system that is a numeric system, and so they have dimension 0.
  * N. dimensions = Number of square brackets ([]).
- The ``shape`` attribute returns the size of the tensor in each dimension (it's an alias for the `size` attribute).
  > It returns the number of components in each dimension. You could see it as the amount of values each subindex could take.
  

## Vectors

In [8]:
print("VECTORS")
vector: torch.Tensor = torch.tensor([1, 0, 1])
print(vector)
print(vector.ndim)
print(vector.shape)
print(vector[1])

VECTORS
tensor([1, 0, 1])
1
torch.Size([3])
tensor(0)


- You can access the components of a tensor by using the square brackets notation. For this purpose, just think of the tensor as an array.
  > Think of the indices inside the brackets as the one to access a component of a tensor. You may access another tensor or a scalar. Be mindful, since you lock or select a component of a dimension per bracket, each bracket will decrease the rank or dimension of the tensor by one.

> WARNING: The tensors are not printed as matrices, but as arrays. That means that you should read the rows as columns and the columns as rows. This is because the tensors are not matrices, but multi-dimensional arrays in Pytorch.

## Matrices

In [33]:
print("MATRICES")
matrix: torch.Tensor = torch.tensor([[1, 2, -3, 4], [5, -6, -7, 8], [-10, -20, 30, 40], [0, 0, 0, 0]])
print(matrix)
print(matrix.dim()) #* Equivalent to .ndim
print(matrix.size()) #* Equivalent to .shape
print(matrix[3]) #* Vector in the fourth component
print(matrix[0][0]) #* First scalar of the vector in the first component.
matrix2: torch.Tensor = torch.tensor(data=[[2, 2], [2, 3]], dtype=torch.float)
# matrix2 = matrix2.float()
print(torch.det(matrix2)) #* Determinant of the matrix

MATRICES
tensor([[  1,   2,  -3,   4],
        [  5,  -6,  -7,   8],
        [-10, -20,  30,  40],
        [  0,   0,   0,   0]])
2
torch.Size([4, 4])
tensor([0, 0, 0, 0])
tensor(1)
tensor([[2., 2., 3.],
        [2., 3., 4.]])


- `torch.det()` calculates the determinant of a matrix. It should be noted that the tensor must have floating-point data type, which can be achieved by setting the parameter `dtype` to any floating-point `dtype` (e.g., `torch.float32`), by using the `.float()` or `.double()` methods of `Tensor` (equivalent to `self.to(torch.float32)` and `self.to(torch.float64)`, respectively), or by adding a decimal point to at least one entry.

- Now, despite the function `torch.tensor()` returning an instance of the `torch.Tensor` class, it is different from calling the constructor of the `Tensor` class:
  - `tensor()` accepts the `device` argument which allows you to specify where the tensor will be stored (CPU or GPU), whereas the constructor does not.
  - By default, any tensor created with `tensor()` will have the `requires_grad` attribute set to `False`, i.e., a **leaf tensor**. In Pytorch, this means the tensor doesn't use the autograd engine to compute gradients (SHOULD DIVE DEEPER INTO THIS). In contrast, the constructor will set this attribute to `True`.
  - The `dtype` argument is also exclusively accepted by `tensor()`, which allows you to specify the data type of the tensor. However, if not specified, it will infer the data type from the input data.
- The key takeaway from the docs is that the `Tensor` class is a base class and initializing them with the constructor is "discouraged". Multiple ways of creating a tensor are provided [here](https://pytorch.org/docs/stable/tensors.html#tensor-class-reference).

In [29]:
print("TENSORS (3D+)")
tensor_r3: torch.Tensor = torch.rand([2, 3, 3])
print(tensor_r3)
tensor_r4: torch.Tensor = torch.rand([2, 2, 2, 3])
print(tensor_r4) #* Rank 4 tensor containing two rank 3 tensors that contain two matrices with two shape 3 (3 axis) vectors each.

TENSORS (3D+)
tensor([[[0.4816, 0.6169, 0.4486],
         [0.5777, 0.0164, 0.9253],
         [0.9609, 0.2100, 0.9207]],

        [[0.1376, 0.7634, 0.9645],
         [0.7217, 0.6080, 0.6722],
         [0.0276, 0.5667, 0.4058]]])
tensor([[[[0.2580, 0.8096, 0.9096],
          [0.7735, 0.1770, 0.2787]],

         [[0.3462, 0.2957, 0.7506],
          [0.6468, 0.5747, 0.4183]]],


        [[[0.7337, 0.0637, 0.9802],
          [0.8396, 0.7473, 0.1529]],

         [[0.6176, 0.9156, 0.7299],
          [0.4805, 0.5894, 0.2401]]]])


As you can see, creating higher-dimensional or higher-ranked tensors is just a matter of adding more square brackets, and to intepret a rank-nth tensor as a collection of rank-(n-1)th tensors and such as a collection of rank-(n-2)th tensors and so on, until you reach scalars.

- `torch.rand(Sequence[int])` is a way to create a tensor with random values from a uniform distribution in the range [0, 1) and shape `Sequence[int]`.